main:
  - name: Acerca de
    url: '#about'
    weight: 1
  - name: Posts
    url: /posts/
    weight: 2
  - name: Curso de análisis cunatitativo de texto 🔥
    url: "https://jmtoral.github.io/text_mining_2021/index.html"
    weight: 3